"""Create tables

Revision ID: 23ee408530c7
Revises: 
Create Date: 2024-11-19 12:46:16.805644

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "23ee408530c7"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cargo_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "cargo_rates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("rate", sa.Float(), nullable=False),
        sa.Column("dt", sa.Date(), nullable=False),
        sa.Column("cargo_type_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cargo_type_id"],
            ["cargo_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cargo_type_id", "dt"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cargo_rates")
    op.drop_table("cargo_types")
    # ### end Alembic commands ###
